version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bcd-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bcd
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ddl-dml.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: